# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import Conversion
    from ._models_py3 import ConversionInputSettings
    from ._models_py3 import ConversionList
    from ._models_py3 import ConversionOutput
    from ._models_py3 import ConversionOutputSettings
    from ._models_py3 import ConversionSettings
    from ._models_py3 import CreateConversionSettings
    from ._models_py3 import CreateSessionSettings
    from ._models_py3 import Error
    from ._models_py3 import ErrorResponse
    from ._models_py3 import SessionProperties
    from ._models_py3 import SessionsList
    from ._models_py3 import UpdateSessionSettings
except (SyntaxError, ImportError):
    from ._models import Conversion  # type: ignore
    from ._models import ConversionInputSettings  # type: ignore
    from ._models import ConversionList  # type: ignore
    from ._models import ConversionOutput  # type: ignore
    from ._models import ConversionOutputSettings  # type: ignore
    from ._models import ConversionSettings  # type: ignore
    from ._models import CreateConversionSettings  # type: ignore
    from ._models import CreateSessionSettings  # type: ignore
    from ._models import Error  # type: ignore
    from ._models import ErrorResponse  # type: ignore
    from ._models import SessionProperties  # type: ignore
    from ._models import SessionsList  # type: ignore
    from ._models import UpdateSessionSettings  # type: ignore

from ._remote_rendering_rest_client_enums import (
    ConversionStatus,
    SessionSize,
    SessionStatus,
)

__all__ = [
    'Conversion',
    'ConversionInputSettings',
    'ConversionList',
    'ConversionOutput',
    'ConversionOutputSettings',
    'ConversionSettings',
    'CreateConversionSettings',
    'CreateSessionSettings',
    'Error',
    'ErrorResponse',
    'SessionProperties',
    'SessionsList',
    'UpdateSessionSettings',
    'ConversionStatus',
    'SessionSize',
    'SessionStatus',
]
